name: Build and Deploy
on:
  push:
    branches: [main]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: build ${{ matrix.services.appName }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services:
          [
            {
              "repositoryName": "producer",
              "directory": "./Sample.Producer",
              "appName": "producer-containerapp",
              "rgName": "azure-container-app-test",
              "zeroDowntime": true,
            },
            {
              "repositoryName": "consumer",
              "directory": "./Sample.Consumer",
              "appName": "consumer-containerapp",
              "rgName": "azure-container-app-test",
              "zeroDowntime": false,
            },
          ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log into acr registry
        if: github.event_name != 'pull_request'
        run: |
          az acr login -n ${{ secrets.ACR_REGISTRY }}

      - name: Output image tag
        id: image-tag
        run: echo "::set-output name=tag::${{ secrets.ACR_REGISTRY }}/${{ matrix.services.repositoryName }}:${{ github.run_id }}"

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.image-tag.outputs.tag }},${{ secrets.ACR_REGISTRY }}/${{ matrix.services.repositoryName }}:latest
          file: ${{ matrix.services.directory }}/Dockerfile

      - name: Deploy azure container app with downtime
        if: github.event_name != 'pull_request' && matrix.services.zeroDowntime == false
        run: |
          echo "Installing containerapp extension"
          az extension add --name containerapp --upgrade
          echo "Create new revision"
          az containerapp update -n ${{ matrix.services.appName }} -g ${{ matrix.services.rgName }} -i ${{ steps.image-tag.outputs.tag }}

      - name: Deploy azure container app without downtime
        if: github.event_name != 'pull_request' && matrix.services.zeroDowntime == true
        run: |
          echo "Installing containerapp extension"
          az extension add --name containerapp --upgrade
          echo "Get current active revision name"
          currentRevision=$(az containerapp revision list -n ${{ matrix.services.appName }} -g ${{ matrix.services.rgName }} --query "[?properties.active==\`true\`].[name]" -o tsv)
          echo "Set multiple revision mode"
          az containerapp revision set-mode -n ${{ matrix.services.appName }} -g ${{ matrix.services.rgName }} --mode multiple
          echo "Redirect traffic to active revision"
          az containerapp ingress traffic set -n ${{ matrix.services.appName }} -g ${{ matrix.services.rgName }} --revision-weight $currentRevision=100
          az containerapp ingress traffic show -n ${{ matrix.services.appName }} -g ${{ matrix.services.rgName }}
          echo "Create new revision"
          az containerapp update -n ${{ matrix.services.appName }} -g ${{ matrix.services.rgName }} -i ${{ steps.image-tag.outputs.tag }}
          az containerapp ingress traffic show -n ${{ matrix.services.appName }} -g ${{ matrix.services.rgName }}
          echo "Redirect traffic to new revision"	
          az containerapp ingress traffic set -n ${{ matrix.services.appName }} -g ${{ matrix.services.rgName }} --revision-weight latest=100
          echo "Set single revision mode"
          az containerapp revision set-mode -n ${{ matrix.services.appName }} -g ${{ matrix.services.rgName }} --mode single
