name: Trigger auto deployment for producer-containerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/producer-containerapp-AutoDeployTrigger-ae533856-e879-47b1-a0a7-c19ec8b01480.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: acatestregistry.azurecr.io
          username: ${{ secrets.PRODUCERCONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.PRODUCERCONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: acatestregistry.azurecr.io/producer-containerapp:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PRODUCERCONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n producer-containerapp -g azure-container-app-test --server acatestregistry.azurecr.io --username  ${{ secrets.PRODUCERCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.PRODUCERCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n producer-containerapp -g azure-container-app-test --image acatestregistry.azurecr.io/producer-containerapp:${{ github.sha }}
